export * from './alunos.service';
export * from './pacotes.service';
export * from './pagamentos.service';
export * from './grupos-musculares.service';
export * from './exercicios.service';
export * from './treino.service';
export * from './avaliacao-fisica.service';
export * from './dieta-nutricional.service';
export * from './produtos.service';
